name: game

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

dependencies:
  - base >= 4.7 && < 5
  - network
  - bytestring
  - sdl2
  - linear
  - text
  - binary
  - bytestring-conversion

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  game:
    main: Game.hs
    source-dirs: .
    ghc-options:
      - -main-is Game
