name: server

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

dependencies:
  - base >= 4.7 && < 5
  - network
  - bytestring
  - bytestring-conversion
  - stylish-haskell
  - hindent
  - async

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  server:
    main: Server.hs
    source-dirs: .
    ghc-options:
      - -main-is Server
